### ISSUE TITLE
[CoppeliaSim]This release will now stop working

### ISSUE THREAD

**Issue by allbluelai** [lagadic/visp_ros#15]
Hello, I build the source under Ubuntu 18.04 and ROS melodic.

At the first time I run ./coppeliaSim.sh, it works.
The next day, I encounter an issue when I run ./coppeliaSim.sh

How can I solved the problem?

The script is wrriten in ~/catkin_ws/doc/html/tutorial-franka-coppeliasim.html:
```
  $ source ~/catkin_ws/devel/setup.bash
  $ cd ~/Downloads/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04
  $ ./coppeliaSim.sh
```

The issue is shown below.
![Screenshot from 2021-07-17 02-16-32](https://user-images.githubusercontent.com/37734505/126028158-3f54414e-9fb2-4fa9-9c06-c97af4a21205.png)

**Comment by aaoliva** [comment]
Hi,
It seems Coppeliasim 4.1 is no longer working, even on Ubuntu 20.04.
You can download Coppeliasim 4.2 and load the scene from there; I am working with that version since a month and works fine.

Best

**Comment by fspindle** [comment]
I just updated the tutorial to use Coppeliasim 4.2.0.

To get the new version:

```
$ cd ~/catkin_ws/src/visp_ros
$ git pull
$ cd ~/catkin_ws
$ catkin_make
$ rosdoc_lite src/visp_ros
```
The tutorial is available in `~/catkin_ws/doc/html/tutorial-franka-coppeliasim.html`
