### ISSUE TITLE
How to simulate Franka robot for an ETH camera?

### ISSUE THREAD

**Issue by allbluelai** [lagadic/visp_ros#16]
Hello,
I want to simulate Franka robor for an ETH camera. 
How can I modify the frankaSim.ttt file for a ETH camera?
Maybe I want to mark a tag on the Gripper? How can I modify the .ttt file?
Or, is there an example for an ETH camera?

**Comment by fspindle** [comment]
The camera is virtual on CoppeliaSim side. There is no need to modify the .ttt file.
Modifying the .ttt file to add a gripper is possible. You should follow CoppeliaSim tutorials.
