### ISSUE TITLE
How can I communicate with CoppeliaSim?

### ISSUE THREAD

**Issue by allbluelai** [lagadic/visp_ros#18]
Q1 : Is there any way to communicate with CoppeliaSim on the client side (cpp or ROS)?
In the tutorial-franka-coppeliasim-ibvs-apriltag.cpp, I see we can get the camera parameters like g.getCameraInfo( cam ). 
Q2 : How can I get the camera parameters?
Q3 : Is there any way to get the pose/position/rotation of the camera(or other Objects in CoppeliaSim)?

**Comment by fspindle** [comment]
Communication between CoppeliaSim and the client side is done using ROS. You should investigate CoppeliaSim tutorials...
