### ISSUE TITLE
When i "catkin_make -DCMAKE_BUILD_TYPE=Release --pkg visp_ros" error: ‘E_MAX_ITERATIONS_EXCEEDED’ is not a member of ‘KDL::SolverI’

### ISSUE THREAD

**Issue by Ji1Xuan** [lagadic/visp_ros#19]
When I compile this package, I keep getting three errors
Error is as follows：
/home/jixuan/catkin_ws/src/visp_ros/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp: In member function ‘virtual void vpRobotFrankaSim::set_flMe(const vpHomogeneousMatrix&)’:
/home/jixuan/catkin_ws/src/visp_ros/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp:196:27: error: ‘__gnu_cxx::__alloc_traits<std::allocator<KDL::Segment> >::value_type {aka class KDL::Segment}’ has no member named ‘setFrameToTip’
   m_chain_kdl.segments[7].setFrameToTip( f8Me_kdl );
                           ^
/home/jixuan/catkin_ws/src/visp_ros/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp: In member function ‘vpColVector vpRobotFrankaSim::solveIK(const vpHomogeneousMatrix&)’:
/home/jixuan/catkin_ws/src/visp_ros/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp:556:8: error: ‘E_MAX_ITERATIONS_EXCEEDED’ is not a member of ‘KDL::SolverI’
   case KDL::SolverI::E_MAX_ITERATIONS_EXCEEDED:
        ^
/home/jixuan/catkin_ws/src/visp_ros/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp:561:8: error: ‘E_NOT_IMPLEMENTED’ is not a member of ‘KDL::SolverI’
   case KDL::SolverI::E_NOT_IMPLEMENTED:
        ^
visp_ros/CMakeFiles/visp_ros.dir/build.make:110: recipe for target 'visp_ros/CMakeFiles/visp_ros.dir/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp.o' failed
make[2]: *** [visp_ros/CMakeFiles/visp_ros.dir/src/robot/sim-robot/franka/vpRobotFrankaSim.cpp.o] Error 1
CMakeFiles/Makefile2:5021: recipe for target 'visp_ros/CMakeFiles/visp_ros.dir/all' failed
make[1]: *** [visp_ros/CMakeFiles/visp_ros.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by aaoliva** [comment]
Hi,

Have you installed OROCOS KDL library?

make sure you have followed the instructions in this link: 
https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox

**Comment by Ji1Xuan** [comment]
HI,

![1](https://user-images.githubusercontent.com/76504244/128360821-08ce7813-b743-4f57-988e-13a043ca4853.png)
I think i have OROCOS KDL library

**Comment by Ji1Xuan** [comment]
> 你好，
> 
> 您是否安装了 OROCOS KDL 库？
> 
> 确保您已按照此链接中的说明进行操作：[https](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox) :
> [//github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox)



> 你好，
> 
> 您是否安装了 OROCOS KDL 库？
> 
> 确保您已按照此链接中的说明进行操作：[https](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox) :
> [//github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox)

My ROS version is Kinetic and Ubuntu version is 16.04

**Comment by Ji1Xuan** [comment]
> 你好，
> 
> 您是否安装了 OROCOS KDL 库？
> 
> 确保您已按照此链接中的说明进行操作：[https](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox) :
> [//github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox](https://github.com/lagadic/visp_ros/blob/master/doc/tutorial-franka-coppeliasim.dox)

My ROS version is Kinetic and Ubuntu version is 16.04

**Comment by fspindle** [comment]
Ubuntu 16.04 is too old. We support 18.04 and 20.04.
