### ISSUE TITLE
/ws/devel/lib/libvisp_ros.so: undefined reference to `KDL::Segment::setFrameToTip(KDL::Frame const&)'

### ISSUE THREAD

**Issue by RENFAN0706** [lagadic/visp_ros#25]
when i build visp_ros, i meet this error.I want to know if visp_ros didn't support ubuntu16.04.I have installed kdl as instruction.Look forward to your answer,thank you!

**Comment by fspindle** [comment]
`visp_ros` should be supported on Ubuntu 16.04.
What is not supported is the [FrankaSim](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-franka-sim.html) simulator that needs at least `liborocos-kdl` 1.3.1 version packaged for `melodic`.
On `kinetic` the package `liborocos-kdl-dev` brings version 1.3.0.
I will modify the project to be able to build `visp_ros` on `kinetic`.
