### ISSUE TITLE
error in ./tutorial-ros-pioneer-visual-servo.cpp

### ISSUE THREAD

**Issue by AnukritiSinghh** [lagadic/visp_ros#26]
Hi, 
I try to run tutorial-ros-pioneer-visual-servo.cpp, but I am getting the following error and can't understand what the problem is. Can you please help me? 

![image](https://user-images.githubusercontent.com/28527591/146952167-aa4d35eb-a330-43be-bf13-2c48767c7eeb.png)

**Comment by fspindle** [comment]
You are trying to execute a C++ source code file `.cpp`. You need first to build the project.
I suggest that you become familiar with C++ build toolchain and follow ROS [tutorials](http://wiki.ros.org/).
