### ISSUE TITLE
visp for ur

### ISSUE THREAD

**Issue by james2254** [lagadic/visp_ros#3]
Can I do a demo with visp in UR robot for grasping?

**Comment by fspindle** [comment]
Yes. With ViSP you can implement a visual servoing (let say may be pose-based) that brings the arm to the grasping position and publish the velocities as a cmd_vel.

**Comment by fspindle** [comment]
Closed since this is not an issue

**Comment by Abduoit** [comment]
Hi @james2254 have u solved your issue ?

I doing visual servoing with UR5, but I am stuck over the flow, 

-1- I am able now to run `roslaunch visp_auto_tracker tracklive_usb.launch` 
 I can detect the RQ-code's position and orientation. 
 `rostopic echo visp_auto_tracker/object_position`

-2- From this [UR5 diver](https://github.com/ThomasTimm/ur_modern_driver) I can control the real arm with rviz and gazebo.

But I don't know how to combine between them and do visual servoing ???

**Comment by fspindle** [comment]
You should implement a ros node that does the visual servoing. This node should subscribe to the pose published by `visp_auto_tracker`, then compute a position based visual servoing (PBVS) where you have to specify a desired pose to reach. [Here](http://visp-doc.inria.fr/doxygen/visp-daily/servoSimu3D_cdMc_CamVelocity_8cpp-example.html) a good example for PBVS. The node should then publish the velocity computed by `vpServo::computeControlLaw()` to the node that contains the UR5 driver.

[Here](https://github.com/lagadic/demo_pioneer/blob/master/src/visual_servo_pioneer.cpp) a ROS example  that shows how to use the pose published by `visp_auto_tracker` in order to achieve an image based visual servoing.

**Comment by Abduoit** [comment]
@fspindle 
Thanks for clarification 

I prepared a ROS node which can subscribe to topic  `/visp_auto_tracker/object_position` and I can check the topic is subscribed by ROS node from `rostopic info /visp_auto_tracker/object_position`

I don't know how to use the PBVS [example](http://visp-doc.inria.fr/doxygen/visp-daily/servoSimu3D_cdMc_CamVelocity_8cpp-example.html)

Would you please help ?

here's the ROS node that I use to subscribe to `/visp_auto_tracker/object_position`


```
#!/usr/bin/env python
import roslib; roslib.load_manifest('visp_auto_tracker')
import rospy
import tf.transformations
from geometry_msgs.msg import PoseStamped

def callback(msg):
    rospy.loginfo("Received at goal message!")
    rospy.loginfo("Timestamp: " + str(msg.header.stamp))
    rospy.loginfo("frame_id: " + str(msg.header.frame_id))

    # Copying for simplicity
    position = msg.pose.position
    quat = msg.pose.orientation
    rospy.loginfo("Point Position: [ %f, %f, %f ]"%(position.x, position.y, position.z))
    rospy.loginfo("Quat Orientation: [ %f, %f, %f, %f]"%(quat.x, quat.y, quat.z, quat.w))

    # Also print Roll, Pitch, Yaw
    euler = tf.transformations.euler_from_quaternion([quat.x, quat.y, quat.z, quat.w])
    rospy.loginfo("Euler Angles: %s"%str(euler))  

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("/visp_auto_tracker/object_position", PoseStamped, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()
```

**Comment by shrutichakraborty** [comment]
> @fspindle Thanks for clarification
> 
> I prepared a ROS node which can subscribe to topic `/visp_auto_tracker/object_position`
> 
> I don't know how to use the PBVS [example](http://visp-doc.inria.fr/doxygen/visp-daily/servoSimu3D_cdMc_CamVelocity_8cpp-example.html) that you suggested.
> 
> Would you please help ?
> 
> Here's the ROS node that I use to subscribe to `/visp_auto_tracker/object_position`
> 
> ```
> #include <vector>
> 
> #include "ros/ros.h"
> #include "geometry_msgs/PoseStamped.h"
> 
> std::vector<geometry_msgs::PoseStamped::ConstPtr> poses;
> 
> void handle_poses(const geometry_msgs::PoseStamped::ConstPtr& msg)
> {
>   ROS_INFO_STREAM("Position X " << msg->pose.position.x);
>   ROS_INFO_STREAM("Position Y: " << msg->pose.position.y);
>   ROS_INFO_STREAM("Position Z: " << msg->pose.position.z);
>   ROS_INFO_STREAM("Orientation X: " << msg->pose.orientation.x);
>   ROS_INFO_STREAM("Orientation Y: " << msg->pose.orientation.y);
>   ROS_INFO_STREAM("Orientation Z: " << msg->pose.orientation.z);
>   ROS_INFO_STREAM("Orientation W: " << msg->pose.orientation.w);
>   // Use the msg object here to access the pose elements,
>   // like msg->pose.pose.position.x
>   poses.push_back(msg);
> }
> 
> int main(int argc, char **argv)
> {
>   ros::init(argc, argv, "listenerccp");
> 
>   ros::NodeHandle n;
> 
>   ros::Subscriber sub = n.subscribe("/visp_auto_tracker/object_position",
>     1000, handle_poses);
> 
>   ros::spin();
> 
>   return 0;
> }
> ```

hello @Abduoit did you solve your issue? I'm working on the same setup. Where did you get the `visp_auto_tracker` node?
