### ISSUE TITLE
Cannot build libsimExtROSInterface.so

### ISSUE THREAD

**Issue by caesar753** [lagadic/visp_ros#30]
Hello,

I'm not able to build libsimExtROSInterface.so. 
I'm on Ubuntu 20.04 and ROS Noetic
Current CoppeliaSim is 4.4.0, if I follow the tutorial [tutorial](http://docs.ros.org/en/noetic/api/visp_ros/html/tutorial-franka-coppeliasim.html#franka_coppeliasim_install_ros_interface) and download libPlugin from  https://github.com/CoppeliaRobotics/libPlugin.git  in the new libPlugin folder of CoppeliaSim directory there is only a README.md which says

`Files moved to [include.git](https://github.com/CoppeliaRobotics/include)`

and when I try to catikin_make the simROSExtInterface from catkin_ws it returns me an error about CMake not found in include directory of CoppeliaSim, so in CoppeliaSim directory I moved the original include folder and clone the above git

```
cd ~/software/CoppeliaSim/
mv include include_origin
git clone https://github.com/CoppeliaRobotics/include
```
in this way the simExtROSInterface builds correctly but there is no libsimExtROSInterface.so in catkin_ws/devel/lib/, I only find libsimExtROS.so and when I start CoppeliaSim it returns me the error 

`ROS interface was not found.`

**Comment by fspindle** [comment]
The instructions mentioned in the [tutorial](http://docs.ros.org/en/noetic/api/visp_ros/html/tutorial-franka-coppeliasim.html) are outdated for CoppeliaSim is 4.4.0.

- Get ROSInterface node source code
  ```
  $ cd ~/catkin_ws/src/
  $ git clone --recursive https://github.com/CoppeliaRobotics/simExtROSInterface.git \
            --branch coppeliasim-v4.4.0-rev0
  ```

- Build ROSInterface node
  ```
  $ cd ~/catkin_ws
  $ source /opt/ros/noetic/setup.bash
  $ sudo apt-get install python3-pip xsltproc
  $ pip3 install xmlschema
  $ catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release
  ```

- Link ROSInterface to the CoppeliaSim directory
  ```
  $ rm <your folder>/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu20_04/libsimExtROS.so
  $ ln -s devel/lib/libsimExtROS.so <your folder>/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu20_04
  ```

**Comment by caesar753** [comment]
Perhaps you forgot the export command 

`export COPPELIASIM_ROOT_DIR=~/software/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu20_04/`

but it works GREAT! Thanks a lot for your quick answer :-)
